version: '2'
services:
  web:
    build: .
    args: 
      proxy: "http://10.70.20.17:8080"
      sproxy: "http://10.70.20.17:8080"
        
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment: 
      - http_proxy=10.70.20.17:8080
      - https_proxy=10.70.20.17:8080