version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment: 
      - http_proxy=http://10.70.20.17:8080
      - https_proxy=https://10.70.20.17:8080